name: Auto Blog Post

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '0 21 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

- name: 依存関係をインストールする
  run: pip install openai requests beautifulsoup4 python-wordpress-xmlrpc

- name: 実行スクリプト
  env:
    WP_URL: ${{ secrets.WP_URL }}
    WP_USERNAME: ${{ secrets.WP_USERNAME }}
    WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  run: python auto_blog.py


